### ISSUE TITLE
Project features

### ISSUE THREAD

**Issue by joeyoropesa-dev** [piyush2108/youtube-clone#1]
While working on design, is this project have support from the YouTube core part called YouTube Studio for managing videos and uploading new ones and is this app allows for non-logged users to browse and watch YouTube

If all those core features gets successfully implemented and modern UI and animations, this can become the first best official YouTube client app that is cross-platform supported for every devices

This could be like a base for making packages and apps (launchers) that will load dependencies and run the app if you succeed

You will be famous on the internet, trust me - you will have a lot of money via getting so much viewers on YouTube channel so much after you succeed with this cool thing to have

Anyway, I want to thank you for all things you've done even before the new implementations gets implemented and released - you're the best, just continue with your work, you have our bless 🥰✨

**Comment by piyusharmap** [comment]
Thanks for the suggestion. I'll try to add these features as well.
